// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    I18nSwitch: typeof import('./src/components/I18nSwitch.vue')['default']
    TestNav: typeof import('./src/components/TestNav.vue')['default']
  }
}

export { }
